USE [PRUEBA]
GO

/****** Object:  StoredProcedure [ASHPF].[sP_ENCABEZADO_FACTURA_RAPIDA]    Script Date: 15/02/2017 7:44:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [ASHPF].[sP_ENCABEZADO_FACTURA_RAPIDA] 
	-- Add the parameters for the stored procedure here
	@Id_FC	AS INT
	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	

	DECLARE	@TIPO_DOCUMENTO			VARCHAR(1)
	DECLARE	@FACTURA				VARCHAR(50)
	DECLARE	@AUDIT_TRANS_INV		INT
	DECLARE	@ESTA_DESPACHADO		VARCHAR(1)
	DECLARE	@EN_INVESTIGACION		VARCHAR(1)
	DECLARE	@TRANS_ADICIONALES		VARCHAR(1)
	DECLARE	@ESTADO_REMISION		VARCHAR(1)
	DECLARE	@ASIENTO_DOCUMENTO		VARCHAR(10)
	DECLARE	@DESCUENTO_VOLUMEN		DECIMAL(28,8)
	DECLARE	@MONEDA_FACTURA			VARCHAR(1)
	DECLARE	@FECHA_DESPACHO			DATETIME
	DECLARE	@CLASE_DOCUMENTO		VARCHAR(1)
	DECLARE	@FECHA_RECIBIDO			DATETIME
	DECLARE	@COMISION_COBRADOR		DECIMAL(28,8)
	DECLARE	@TOTAL_VOLUMEN			DECIMAL(28,8)
	DECLARE	@TOTAL_PESO				DECIMAL(28,8)
	DECLARE	@MONTO_COBRADO			DECIMAL(28,8)
	DECLARE	@TOTAL_IMPUESTO1		DECIMAL(28,8)
	DECLARE	@FECHA					DATETIME
	DECLARE	@FECHA_ENTREGA			DATETIME
	DECLARE	@TOTAL_IMPUESTO2		DECIMAL(28,8)
	DECLARE	@PORC_DESCUENTO2		DECIMAL(28,8)
	DECLARE	@MONTO_FLETE			DECIMAL(28,8)
	DECLARE	@MONTO_SEGURO			DECIMAL(28,8)
	DECLARE	@MONTO_DOCUMENTACIO		DECIMAL(28,8)
	DECLARE	@TIPO_DESCUENTO1		VARCHAR(1)
	DECLARE	@TIPO_DESCUENTO2		VARCHAR(1)
	DECLARE @MONTO_DESCUENTO1		DECIMAL(28,8)
	DECLARE @MONTO_DESCUENTO2		DECIMAL(28,8)
	DECLARE	@PORC_DESCUENTO1		DECIMAL(28,8)
	DECLARE	@TOTAL_FACTURA			DECIMAL(28,8)
	DECLARE	@FECHA_PEDIDO			DATETIME
	DECLARE	@FECHA_ORDEN			DATETIME
	DECLARE	@TOTAL_MERCADERIA		DECIMAL(28,8)
	DECLARE	@COMISION_VENDEDOR		DECIMAL(28,8)
	DECLARE	@FECHA_HORA				DATETIME
	DECLARE	@TOTAL_UNIDADES			DECIMAL(28,8)
	DECLARE	@NUMERO_PAGINAS			SMALLINT
	DECLARE	@TIPO_CAMBIO			DECIMAL(28,8)
	DECLARE @ANULADA				VARCHAR(1)
	DECLARE	@MODULO					VARCHAR(4)
	DECLARE	@CARGADO_CG				VARCHAR(1)
	DECLARE	@CARGADO_CXC			VARCHAR(1)
	DECLARE	@EMBARCAR_A				VARCHAR(80)
	DECLARE	@DIREC_EMBARQUE			VARCHAR(8)
	DECLARE	@MULTIPLICADOR_EV		SMALLINT
	DECLARE	@VERSION_NP				INT
	DECLARE	@MONEDA					VARCHAR(1)
	DECLARE	@NIVEL_PRECIO			VARCHAR(12)
	DECLARE	@COBRADA				VARCHAR(1)
	DECLARE	@RUTA					VARCHAR(4)
	DECLARE	@USUARIO				VARCHAR(25)
	DECLARE	@CONDICION_PAGO			VARCHAR(4)
	DECLARE	@ZONA					VARCHAR(4)
	DECLARE	@VENDEDOR				VARCHAR(4)
	DECLARE	@DOC_CREDITO_CXC		VARCHAR(50)
	DECLARE	@CLIENTE_DIRECCION		VARCHAR(20)
	DECLARE	@CLIENTE_CORPORAC		VARCHAR(20)
	DECLARE	@CLIENTE_ORIGEN			VARCHAR(20)
	DECLARE	@CLIENTE				VARCHAR(20)
	DECLARE	@PAIS					VARCHAR(4)
	DECLARE	@SUBTIPO_DOC_CXC		SMALLINT
	DECLARE	@TIPO_CREDITO_CXC		VARCHAR(3)
	DECLARE	@TIPO_DOC_CXC			VARCHAR(3)
	DECLARE	@FECHA_RIGE				DATETIME
	DECLARE	@USA_DESPACHOS			VARCHAR(1)
	DECLARE	@COBRADOR				VARCHAR(4)
	DECLARE	@DESCUENTO_CASCADA		VARCHAR(1)
	DECLARE	@NoteExistsFlag			TINYINT
	DECLARE	@RecordDate				DATETIME
	DECLARE	@RowPointer				UNIQUEIDENTIFIER
	DECLARE	@CreatedBy				VARCHAR(30)
	DECLARE	@UpdatedBy				VARCHAR(30)
	DECLARE	@CreateDate				DATETIME
	DECLARE	@NOMBRE_CLIENTE			VARCHAR(150)
	DECLARE	@REIMPRESO				INT
	DECLARE	@GENERA_DOC_FE			VARCHAR(1)

	

	DECLARE @Id_PR					INT
	DECLARE @Id_PT					AS NVARCHAR(15)
	DECLARE @Id_LP					INT

	SET NOCOUNT ON;
    
	BEGIN TRY
		BEGIN TRANSACTION;

									

						--- FETCH DATA FROM FACTURA
						SET @TIPO_DOCUMENTO		='F'
						SET @FACTURA			=(SELECT UDF_Factura_E FROM H1_ASHONPLAFA_387.dbo.FC WHERE Id_FC=@Id_FC)
						SET @ESTA_DESPACHADO	='N'
						SET @EN_INVESTIGACION	='N'
						SET @TRANS_ADICIONALES	='N'
						SET @ESTADO_REMISION	='N'
						SET @DESCUENTO_VOLUMEN	=0.00000000
						SET @MONEDA_FACTURA		=(SELECT MONEDA_NIVEL FROM ASHPF.GLOBALES_FA)
						SET @FECHA_DESPACHO		=(SELECT Fecha_Registro FROM H1_ASHONPLAFA_387.dbo.FC WHERE Id_FC=@Id_FC)
						SET @FECHA_RECIBIDO		=(SELECT Fecha_Registro FROM H1_ASHONPLAFA_387.dbo.FC WHERE Id_FC=@Id_FC)
						SET @FECHA				=(SELECT Fecha_Registro FROM H1_ASHONPLAFA_387.dbo.FC WHERE Id_FC=@Id_FC)
						SET @FECHA_ENTREGA		=(SELECT Fecha_Registro FROM H1_ASHONPLAFA_387.dbo.FC WHERE Id_FC=@Id_FC)
						SET @FECHA_PEDIDO		=(SELECT Fecha_Registro FROM H1_ASHONPLAFA_387.dbo.FC WHERE Id_FC=@Id_FC)
						SET @FECHA_HORA			=(SELECT Fecha_Registro FROM H1_ASHONPLAFA_387.dbo.FC WHERE Id_FC=@Id_FC)
						SET @FECHA_RIGE			=(SELECT Fecha_Registro FROM H1_ASHONPLAFA_387.dbo.FC WHERE Id_FC=@Id_FC)
						SET @USUARIO			=(SELECT Usuario_Registro FROM H1_ASHONPLAFA_387.dbo.FC WHERE Id_FC=@Id_FC)
						SET @CONDICION_PAGO		=(SELECT MetodoPago FROM H1_ASHONPLAFA_387.dbo.FC WHERE Id_FC=@Id_FC)
						SET @CLASE_DOCUMENTO	='N'
						SET @COMISION_COBRADOR	=0.00000000
						SET @TOTAL_VOLUMEN		=0.00000000
						SET @TOTAL_PESO			=0.00000000
						SET @MONTO_COBRADO		=0.00000000
						SET @TOTAL_IMPUESTO1	=0.00000000
						SET @TOTAL_IMPUESTO2	=0.00000000
						SET @PORC_DESCUENTO1	=0.00000000
						SET @PORC_DESCUENTO2	=0.00000000
						SET @MONTO_FLETE		=0.00000000
						SET @MONTO_SEGURO		=0.00000000
						SET @MONTO_DOCUMENTACIO	=0.00000000
						SET @TIPO_DESCUENTO1	='P'
						SET @TIPO_DESCUENTO2	='P'
						SET @MONTO_DESCUENTO1	=0.00000000
						SET @MONTO_DESCUENTO2	=0.00000000
						SET @TOTAL_FACTURA		=(SELECT SUM(Cantidad*PrecioUnitario) FROM H1_ASHONPLAFA_387.dbo.FCDT WHERE Id_FC=@Id_FC)
						SET @TOTAL_MERCADERIA	=@TOTAL_FACTURA
						SET @COMISION_VENDEDOR	=0.00000000
						SET @TOTAL_UNIDADES		=(SELECT SUM(Cantidad) FROM H1_ASHONPLAFA_387.dbo.FCDT WHERE Id_FC=@Id_FC)
						SET @NUMERO_PAGINAS		=1
						SET @TIPO_CAMBIO		=(SELECT MH.MONTO FROM   PRUEBA.ASHPF.MONEDA_HIST AS MH WHERE  MH.MONEDA = 'DLR' AND MH.FECHA = 
												 (SELECT MAX(FECHA) FROM   PRUEBA.ASHPF.MONEDA_HIST  WHERE  CONVERT(CHAR(8),FECHA,112) <= CONVERT(CHAR(8),GETDATE(),112) AND MONEDA = 'DLR'))
						SET @ANULADA			='N'
						SET @MODULO				=(SELECT PAQUETE FROM ASHPF.GLOBALES_FA)
						SET @CARGADO_CG			='S'
						SET @CARGADO_CXC		='N'
						SET @Id_PT				=(SELECT PR.Id_PT FROM H1_ASHONPLAFA_387.dbo.FC AS PR WHERE PR.Id_FC=@Id_FC)
						SET @EMBARCAR_A			=(SELECT C.NOMBRE FROM ASHPF.CLIENTE AS C WHERE C.CLIENTE=@Id_PT)
						SET @MULTIPLICADOR_EV	=1
						SET @Id_LP				=(SELECT PR.Id_LP FROM H1_ASHONPLAFA_387.dbo.FC AS PR WHERE PR.Id_FC=@Id_FC)
						SET @NIVEL_PRECIO		=(SELECT NIVEL_PRECIO FROM PRUEBA.ASHPF.NIVEL_PRECIO AS NP	WHERE NP.Id_NIVEL_PRECIO =@Id_LP )
						SET @VERSION_NP			=(SELECT [VERSION] FROM ASHPF.VERSION_NIVEL WHERE ESTADO='C' AND NIVEL_PRECIO=@NIVEL_PRECIO)
						SET @MONEDA				=(SELECT MONEDA FROM PRUEBA.ASHPF.NIVEL_PRECIO AS NP	WHERE NP.Id_NIVEL_PRECIO =@Id_LP )
						SET @Id_PR				=(SELECT PR.Id_PR FROM H1_ASHONPLAFA_387.dbo.FC AS PR WHERE PR.Id_FC=@Id_FC)
						SET @COBRADOR			=(SELECT CB.Referencia1 FROM H1_ASHONPLAFA_387.dbo.PR AS CB WHERE CB.Id_PR=@Id_PR)
						SET @PAIS				='0001'
						SET @RUTA				=(SELECT C.RUTA FROM ASHPF.CLIENTE AS C WHERE C.CLIENTE=@Id_PT  )
						SET @ZONA				=(SELECT C.ZONA FROM ASHPF.CLIENTE AS C WHERE C.CLIENTE=@Id_PT  )
						SET @VENDEDOR			='ND'
						SET @CLIENTE_DIRECCION	=@Id_PT
						SET @CLIENTE_CORPORAC	=@Id_PT
						SET @CLIENTE_ORIGEN		=@Id_PT
						SET @CLIENTE			=@Id_PT
						SET @USA_DESPACHOS		='N'
						SET @COBRADA			='S'
						SET @DESCUENTO_CASCADA	='N'
						SET @REIMPRESO			=0			
						SET @GENERA_DOC_FE		='N'		
						SET @SUBTIPO_DOC_CXC	=0	
						SET @TIPO_DOC_CXC		='FAC' 

							SELECT 
								@TIPO_DOCUMENTO,@FACTURA,@ESTA_DESPACHADO,@EN_INVESTIGACION,@TRANS_ADICIONALES,@ESTADO_REMISION,F.UDF_Asiento,@DESCUENTO_VOLUMEN,
								@MONEDA_FACTURA,@FECHA_DESPACHO,@CLASE_DOCUMENTO,@FECHA_RECIBIDO,@COMISION_COBRADOR,@TOTAL_VOLUMEN,
								@TOTAL_PESO,@MONTO_COBRADO,@TOTAL_IMPUESTO1,@FECHA,@FECHA_ENTREGA,@TOTAL_IMPUESTO2,@PORC_DESCUENTO2,
								@MONTO_FLETE,@MONTO_SEGURO,@MONTO_DOCUMENTACIO,@TIPO_DESCUENTO1,@TIPO_DESCUENTO2,@MONTO_DESCUENTO1,@MONTO_DESCUENTO2,@PORC_DESCUENTO1,
								@TOTAL_FACTURA,@FECHA_PEDIDO,@TOTAL_MERCADERIA,@COMISION_VENDEDOR,@FECHA_HORA,@TOTAL_UNIDADES,
								@NUMERO_PAGINAS,@TIPO_CAMBIO,@ANULADA,@MODULO,@CARGADO_CG,@CARGADO_CXC,@EMBARCAR_A,@MULTIPLICADOR_EV,@VERSION_NP,@MONEDA,@NIVEL_PRECIO,
								@COBRADOR,@RUTA,@USUARIO,@CONDICION_PAGO,@ZONA,@VENDEDOR,@CLIENTE_DIRECCION,@CLIENTE_CORPORAC,
								@CLIENTE_ORIGEN,@CLIENTE,@PAIS,@FECHA_RIGE,@USA_DESPACHOS,@COBRADA,@DESCUENTO_CASCADA,@REIMPRESO,@GENERA_DOC_FE,@SUBTIPO_DOC_CXC,@TIPO_DOC_CXC
						
								FROM H1_ASHONPLAFA_387.dbo.FC AS F WHERE F.Id_FC=@Id_FC



						INSERT INTO ASHPF.FACTURA
							(TIPO_DOCUMENTO,FACTURA,ESTA_DESPACHADO,EN_INVESTIGACION,TRANS_ADICIONALES,ESTADO_REMISION,ASIENTO_DOCUMENTO
							,DESCUENTO_VOLUMEN,MONEDA_FACTURA,FECHA_DESPACHO,CLASE_DOCUMENTO,FECHA_RECIBIDO,COMISION_COBRADOR,TOTAL_VOLUMEN
							,TOTAL_PESO,MONTO_COBRADO,TOTAL_IMPUESTO1,FECHA,FECHA_ENTREGA,TOTAL_IMPUESTO2,PORC_DESCUENTO2,MONTO_FLETE
							,MONTO_SEGURO,MONTO_DOCUMENTACIO,TIPO_DESCUENTO1,TIPO_DESCUENTO2,MONTO_DESCUENTO1,MONTO_DESCUENTO2
							,PORC_DESCUENTO1,TOTAL_FACTURA,FECHA_PEDIDO,TOTAL_MERCADERIA,COMISION_VENDEDOR,FECHA_HORA,TOTAL_UNIDADES
							,NUMERO_PAGINAS,TIPO_CAMBIO,ANULADA,MODULO,CARGADO_CG,CARGADO_CXC,EMBARCAR_A,MULTIPLICADOR_EV,VERSION_NP
							,MONEDA,NIVEL_PRECIO,COBRADOR,RUTA,USUARIO,CONDICION_PAGO,ZONA,VENDEDOR,CLIENTE_DIRECCION,CLIENTE_CORPORAC
							,CLIENTE_ORIGEN,CLIENTE,PAIS,FECHA_RIGE,USA_DESPACHOS,COBRADA,DESCUENTO_CASCADA,REIMPRESO,GENERA_DOC_FE,SUBTIPO_DOC_CXC,TIPO_DOC_CXC)
						VALUES
							(@TIPO_DOCUMENTO,@FACTURA,@ESTA_DESPACHADO,@EN_INVESTIGACION,@TRANS_ADICIONALES,@ESTADO_REMISION,@ASIENTO_DOCUMENTO
							,@DESCUENTO_VOLUMEN,@MONEDA_FACTURA,@FECHA_DESPACHO,@CLASE_DOCUMENTO,@FECHA_RECIBIDO,@COMISION_COBRADOR,@TOTAL_VOLUMEN
							,@TOTAL_PESO,@MONTO_COBRADO,@TOTAL_IMPUESTO1,@FECHA,@FECHA_ENTREGA,@TOTAL_IMPUESTO2,@PORC_DESCUENTO2,@MONTO_FLETE
							,@MONTO_SEGURO,@MONTO_DOCUMENTACIO,@TIPO_DESCUENTO1,@TIPO_DESCUENTO2,@MONTO_DESCUENTO1,@MONTO_DESCUENTO2
							,@PORC_DESCUENTO1,@TOTAL_FACTURA,@FECHA_PEDIDO,@TOTAL_MERCADERIA,@COMISION_VENDEDOR,@FECHA_HORA,@TOTAL_UNIDADES
							,@NUMERO_PAGINAS,@TIPO_CAMBIO,@ANULADA,@MODULO,@CARGADO_CG,@CARGADO_CXC,@EMBARCAR_A,@MULTIPLICADOR_EV,@VERSION_NP
							,@MONEDA,@NIVEL_PRECIO,@COBRADOR,@RUTA,@USUARIO,@CONDICION_PAGO,@ZONA,@VENDEDOR,@CLIENTE_DIRECCION,@CLIENTE_CORPORAC
							,@CLIENTE_ORIGEN,@CLIENTE,@PAIS,@FECHA_RIGE,@USA_DESPACHOS,@COBRADA,@DESCUENTO_CASCADA,@REIMPRESO,@GENERA_DOC_FE,@SUBTIPO_DOC_CXC,@TIPO_DOC_CXC)

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
		ROLLBACK TRANSACTION;
		END
		EXECUTE ASHPF.Sp_LogError;
	END CATCH;
	
END

GO

