USE [AHPF_HN]
GO

/****** Object:  StoredProcedure [ASHPF].[sP_INSERT_SALDO]    Script Date: 5/11/2017 3:55:27 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [ASHPF].[sP_INSERT_SALDO]

	@ASIENTO		AS VARCHAR(10)
	
AS
BEGIN 

	SET NOCOUNT ON;
		
		--- VARIABLES TEMPORALES PARA CARGA DE ASIENTO 

		DECLARE @TEMP_ASIENTO				VARCHAR(10)
		DECLARE @TEMP_CENTRO_COSTO			VARCHAR(25)
		DECLARE @TEMP_CUENTA_CONTABLE		VARCHAR(25)	
		DECLARE @TEMP_DEBITO				DECIMAL(28,8)
		DECLARE @TEMP_CREDITO				DECIMAL(28,8)
		DECLARE @TEMP_DEBITO_DOLAR			DECIMAL(28,8)
		DECLARE @TEMP_CREDITO_DOLAR			DECIMAL(28,8)
		DECLARE @TEMP_DEBITO_UNIDADES		DECIMAL(28,8)
		DECLARE @TEMP_CREDITO_UNIDADES		DECIMAL(28,8)
		DECLARE @TEMP_CONSECUTIVO			INT
		DECLARE @TEMP_FECHA					DATETIME
		DECLARE @TEMP_FECHA_PERIODO			DATETIME
		DECLARE @TEMP_DEBITO_LOCAL			DECIMAL(28,8)
		DECLARE @TEMP_CREDITO_LOCAL			DECIMAL(28,8)
		DECLARE @TEMP_NIT					VARCHAR(20)
		DECLARE @TEMP_CONTABILIDAD			VARCHAR(1)
		DECLARE @TEMP_TIPO					VARCHAR(1)
		DECLARE @TEMP_CreatedBy				VARCHAR(30)
		DECLARE @TEMP_UpdatedBy				VARCHAR(30)
		DECLARE @TEMP_NoteExistsFlag		INT
		DECLARE @TEMP_RecordDate			DATETIME
		DECLARE @TEMP_RowPointer			UNIQUEIDENTIFIER
		DECLARE @TEMP_CreateDate			DATETIME

		DECLARE @PERIODO_ESTADO				INT
		DECLARE @ULTIMO_PERIODO				DATETIME

		--- VARIABLES PARA ITERACION DE LINEAS EN ASIENTO 

		DECLARE @A					AS	INT
			SET @A = 1
		DECLARE	@Id_A				AS	INT

		--- VARIABLES TEMPORALES PARA SALDO POR CUENTAS

		DECLARE @TEMP_CENTRO_COSTO_S		VARCHAR(25)
		DECLARE @TEMP_CUENTA_CONTABLE_S		VARCHAR(25)
		DECLARE @TEMP_FECHA_S				DATETIME
		DECLARE @TEMP_SALDO_FISC_LOCAL_S	DECIMAL(28,8)
		DECLARE @TEMP_SALDO_FISC_DOLAR_S	DECIMAL(28,8)
		DECLARE @TEMP_SALDO_CORP_LOCAL_S	DECIMAL(28,8)
		DECLARE @TEMP_SALDO_CORP_DOLAR_S	DECIMAL(28,8)
		DECLARE @TEMP_DEBITO_FISC_LOCAL_S	DECIMAL(28,8)
		DECLARE @TEMP_CREDITO_FISC_LOCAL_S	DECIMAL(28,8)
		DECLARE @TEMP_DEBITO_CORP_LOCAL_S	DECIMAL(28,8)
		DECLARE @TEMP_CREDITO_CORP_LOCAL_S	DECIMAL(28,8)
		DECLARE @TEMP_DEBITO_FISC_DOLAR_S	DECIMAL(28,8)
		DECLARE @TEMP_CREDITO_FISC_DOLAR_S	DECIMAL(28,8)
		DECLARE @TEMP_DEBITO_CORP_DOLAR_S	DECIMAL(28,8)
		DECLARE @TEMP_CREDITO_CORP_DOLAR_S	DECIMAL(28,8)
		DECLARE @TEMP_SALDO_FISC_UND_S		DECIMAL(28,8)
		DECLARE @TEMP_SALDO_CORP_UND_S		DECIMAL(28,8)
		DECLARE @TEMP_DEBITO_FISC_UND_S		DECIMAL(28,8)
		DECLARE @TEMP_CREDITO_FISC_UND_S	DECIMAL(28,8)
		DECLARE @TEMP_DEBITO_CORP_UND_S		DECIMAL(28,8)
		DECLARE @TEMP_CREDITO_CORP_UND_S	DECIMAL(28,8)


	BEGIN TRY
		BEGIN TRANSACTION;

				--- TANLA PARA CARGA DE LINEAS DE ASIENTO PARA BALANCE  DE COMPROBACION 

				DECLARE @ASIENTO_LINEAS AS TABLE(
				ID INT IDENTITY(1,1) PRIMARY KEY,
				CONSECUTIVO						INT,
				ASIENTO							VARCHAR(10),
				CENTRO_COSTO					VARCHAR(25),
				CUENTA_CONTABLE					VARCHAR(25),
				FECHA							DATETIME,
				DEBITO_LOCAL					DECIMAL(28,8),
				CREDITO_LOCAL					DECIMAL(28,8),
				DEBITO_DOLAR					DECIMAL(28,8),
				CREDITO_DOLAR					DECIMAL(28,8),
				DEBITO_UNIDADES					DECIMAL(28,8),
				CREDITO_UNIDADES				DECIMAL(28,8),
				NIT								VARCHAR(20),
				CONTABILIDAD					VARCHAR(1),
				TIPO							VARCHAR(1),
				FECHA_PERIODO					DATETIME,
				CreatedBy						VARCHAR(30),
				UpdatedBy						VARCHAR(30)
				)


				--- CARGA DE LINEAS DE ASIENTO A TABLA TEMPORAL 

				INSERT INTO @ASIENTO_LINEAS
				(CONSECUTIVO,ASIENTO,CENTRO_COSTO,CUENTA_CONTABLE,FECHA,DEBITO_LOCAL,CREDITO_LOCAL,DEBITO_DOLAR,CREDITO_DOLAR,DEBITO_UNIDADES,CREDITO_UNIDADES,NIT,CONTABILIDAD,
				TIPO,FECHA_PERIODO,CreatedBy,UpdatedBy)

									SELECT 
									M1.CONSECUTIVO, 
									M1.ASIENTO, 
									M1.CENTRO_COSTO, 
									M1.CUENTA_CONTABLE, 
									M1.FECHA, 
									ISNULL(M1.DEBITO_LOCAL,0)		AS DEBITO_LOCAL,
									ISNULL(M1.CREDITO_LOCAL,0)		AS CREDITO_LOCAL,
									ISNULL(M1.DEBITO_DOLAR,0)		AS DEBITO_DOLAR,
									ISNULL(M1.CREDITO_DOLAR,0)		AS CREDITO_DOLAR,
									ISNULL(M1.DEBITO_UNIDADES,0)	AS DEBITO_UNIDADES,
									ISNULL(M1.CREDITO_UNIDADES,0)	AS CREDITO_UNIDADES,
									M1.NIT, 
									M1.CONTABILIDAD,
									([AHPF_HN].[ASHPF].[GET_TIPOSALDO] (M1.ASIENTO,M1.CENTRO_COSTO,M1.CUENTA_CONTABLE)) AS TIPO, 
									(SELECT MIN(P.FECHA_FINAL) FROM ASHPF.PERIODO_CONTABLE AS P 
									WHERE P.FECHA_FINAL >= M1.FECHA) AS FECHA_PERIODO, 
									M1.CreatedBy, 
									M1.UpdatedBy

									FROM AHPF_HN.ASHPF.MAYOR AS M1
									WHERE M1.TIPO_ASIENTO='PING' 
									AND M1.ORIGEN='FA'
									AND M1.ASIENTO=@ASIENTO
									ORDER BY M1.CONSECUTIVO


							---------------------------------------------------------------------------------------
							---------------------------------------------------------------------------------------
							---------------------------------------------------------------------------------------
														--- INICIA EL PROCESO ---
							---------------------------------------------------------------------------------------

							SELECT @Id_A = COUNT(*) FROM  @ASIENTO_LINEAS

							WHILE @A <= @Id_A
											BEGIN

												SELECT 
												@TEMP_CONSECUTIVO				=	L.CONSECUTIVO,
												@TEMP_ASIENTO					=	L.ASIENTO,
												@TEMP_CENTRO_COSTO				=	L.CENTRO_COSTO,
												@TEMP_CUENTA_CONTABLE			=	L.CUENTA_CONTABLE,
												@TEMP_FECHA						=	L.FECHA,
												@TEMP_DEBITO_LOCAL				=	L.DEBITO_LOCAL,
												@TEMP_CREDITO_LOCAL				=	L.CREDITO_LOCAL,
												@TEMP_DEBITO_DOLAR				=	L.DEBITO_DOLAR,
												@TEMP_CREDITO_DOLAR				=	L.CREDITO_DOLAR,
												@TEMP_DEBITO_UNIDADES			=	L.DEBITO_UNIDADES,
												@TEMP_CREDITO_UNIDADES			=	L.CREDITO_UNIDADES,
												@TEMP_NIT						=	L.NIT,
												@TEMP_CONTABILIDAD				=	L.CONTABILIDAD,
												@TEMP_TIPO						=	L.TIPO,
												@TEMP_FECHA_PERIODO				=	L.FECHA_PERIODO,
												@TEMP_CreatedBy					=	L.CreatedBy,
												@TEMP_UpdatedBy					=	L.UpdatedBy,
												@TEMP_NoteExistsFlag			=	0,	
												@TEMP_RecordDate				=	GETDATE(),
												@TEMP_RowPointer				=	NEWID(),
												@TEMP_CreateDate				=	GETDATE()

												FROM @ASIENTO_LINEAS AS L	WHERE L.ID = @A


												--- VALIDACION PARA DETERMINAR SI PERIODO CONTABLE EXISTE 

												SET @PERIODO_ESTADO	= (SELECT COUNT(*) 	FROM ASHPF.SALDO 
												WHERE 
												FECHA			=@TEMP_FECHA_PERIODO			AND 
												CENTRO_COSTO	=@TEMP_CENTRO_COSTO				AND 
												CUENTA_CONTABLE	=@TEMP_CUENTA_CONTABLE)	

												-----------------------------------------------------------------------------------------
												------------------------- PERIODO CONTABLE NO EXISTE    ---------------------------------
												-----------------------------------------------------------------------------------------

												IF @PERIODO_ESTADO = 0

												BEGIN

													--- OBTENER ULTIMO PERIODO CONTABLE POR CENTRO COSTO Y CUENTA CONTABLE

													SET @ULTIMO_PERIODO = (
													SELECT MAX(FECHA)
													FROM AHPF_HN.ASHPF.SALDO 
													WHERE 
													CENTRO_COSTO=@TEMP_CENTRO_COSTO AND CUENTA_CONTABLE=@TEMP_CUENTA_CONTABLE)

													--- OBTENER SALDO POR CENTRO COSTO Y CUENTA CONTABLE ---

													SELECT 
													@TEMP_CENTRO_COSTO_S			=	S0.CENTRO_COSTO, 
													@TEMP_CUENTA_CONTABLE_S			=	S0.CUENTA_CONTABLE,
													@TEMP_FECHA_S					=	S0.FECHA, 
													@TEMP_SALDO_FISC_LOCAL_S		=	S0.SALDO_FISC_LOCAL,
													@TEMP_SALDO_FISC_DOLAR_S		=	S0.SALDO_FISC_DOLAR,
													@TEMP_SALDO_CORP_LOCAL_S		=	S0.SALDO_CORP_LOCAL,
													@TEMP_SALDO_CORP_DOLAR_S		=	S0.SALDO_CORP_DOLAR,
													@TEMP_DEBITO_FISC_LOCAL_S		=	S0.DEBITO_FISC_LOCAL,
													@TEMP_CREDITO_FISC_LOCAL_S		=	S0.CREDITO_FISC_LOCAL,
													@TEMP_DEBITO_CORP_LOCAL_S		=	S0.DEBITO_CORP_LOCAL,
													@TEMP_CREDITO_CORP_LOCAL_S		=	S0.CREDITO_CORP_LOCAL,	
													@TEMP_DEBITO_FISC_DOLAR_S		=	S0.DEBITO_FISC_DOLAR,	
													@TEMP_CREDITO_FISC_DOLAR_S		=	S0.CREDITO_FISC_DOLAR,
													@TEMP_DEBITO_CORP_DOLAR_S		=	S0.DEBITO_CORP_DOLAR,
													@TEMP_CREDITO_CORP_DOLAR_S		=	S0.CREDITO_CORP_DOLAR,
													@TEMP_SALDO_FISC_UND_S			=	S0.SALDO_FISC_UND,
													@TEMP_SALDO_CORP_UND_S			=	S0.SALDO_CORP_UND,
													@TEMP_DEBITO_FISC_UND_S			=	S0.DEBITO_FISC_UND,
													@TEMP_CREDITO_FISC_UND_S		=	S0.CREDITO_FISC_UND,
													@TEMP_DEBITO_CORP_UND_S			=	S0.DEBITO_CORP_UND,
													@TEMP_CREDITO_CORP_UND_S		=	S0.CREDITO_CORP_UND
													
													FROM AHPF_HN.ASHPF.SALDO AS S0
													WHERE S0.CENTRO_COSTO	=	@TEMP_CENTRO_COSTO
													AND S0.CUENTA_CONTABLE	=	@TEMP_CUENTA_CONTABLE 
													AND S0.FECHA			=	@ULTIMO_PERIODO
													ORDER BY FECHA

														--- INICIA LA INSERCION ---

														IF @TEMP_TIPO	=	'C'

															BEGIN

															
																INSERT INTO AHPF_HN.ASHPF.SALDO
																(CENTRO_COSTO,CUENTA_CONTABLE,FECHA,SALDO_FISC_LOCAL,SALDO_FISC_DOLAR,SALDO_CORP_LOCAL
																,SALDO_CORP_DOLAR,DEBITO_FISC_LOCAL,CREDITO_FISC_LOCAL,DEBITO_CORP_LOCAL,CREDITO_CORP_LOCAL
																,DEBITO_FISC_DOLAR,CREDITO_FISC_DOLAR,DEBITO_CORP_DOLAR,CREDITO_CORP_DOLAR,SALDO_FISC_UND
																,SALDO_CORP_UND,DEBITO_FISC_UND,CREDITO_FISC_UND,DEBITO_CORP_UND,CREDITO_CORP_UND,RecordDate,CreatedBy,UpdatedBy,CreateDate)

																VALUES
																(@TEMP_CENTRO_COSTO,@TEMP_CUENTA_CONTABLE,@TEMP_FECHA,@TEMP_SALDO_FISC_LOCAL_S,@TEMP_SALDO_FISC_DOLAR_S,@TEMP_SALDO_CORP_LOCAL_S
																,@TEMP_SALDO_CORP_DOLAR_S,@TEMP_DEBITO_FISC_LOCAL_S,@TEMP_CREDITO_FISC_LOCAL_S,@TEMP_DEBITO_CORP_LOCAL_S,@TEMP_CREDITO_CORP_LOCAL_S
																,@TEMP_DEBITO_FISC_DOLAR_S,@TEMP_CREDITO_FISC_DOLAR_S,@TEMP_DEBITO_CORP_DOLAR_S,@TEMP_CREDITO_CORP_DOLAR_S,@TEMP_SALDO_FISC_UND_S
																,@TEMP_SALDO_CORP_UND_S,@TEMP_DEBITO_FISC_UND_S,@TEMP_CREDITO_FISC_UND_S,@TEMP_DEBITO_CORP_UND_S
																,@TEMP_CREDITO_CORP_UND_S,GETDATE(),@TEMP_CreatedBy,@TEMP_UpdatedBy,GETDATE())

																UPDATE AHPF_HN.ASHPF.SALDO
																SET SALDO_FISC_LOCAL	=	SALDO_FISC_LOCAL	+ @TEMP_CREDITO_LOCAL,
																CREDITO_FISC_LOCAL		=	CREDITO_FISC_LOCAL	+ @TEMP_CREDITO_LOCAL

																WHERE 
																CENTRO_COSTO		=	@TEMP_CENTRO_COSTO_S		AND
																CUENTA_CONTABLE		=	@TEMP_CUENTA_CONTABLE_S		AND
																FECHA				=	@TEMP_FECHA_S


															
															END	

														IF @TEMP_TIPO	=	'D'

															BEGIN

															
																INSERT INTO AHPF_HN.ASHPF.SALDO
																(CENTRO_COSTO,CUENTA_CONTABLE,FECHA,SALDO_FISC_LOCAL,SALDO_FISC_DOLAR,SALDO_CORP_LOCAL
																,SALDO_CORP_DOLAR,DEBITO_FISC_LOCAL,CREDITO_FISC_LOCAL,DEBITO_CORP_LOCAL,CREDITO_CORP_LOCAL
																,DEBITO_FISC_DOLAR,CREDITO_FISC_DOLAR,DEBITO_CORP_DOLAR,CREDITO_CORP_DOLAR,SALDO_FISC_UND
																,SALDO_CORP_UND,DEBITO_FISC_UND,CREDITO_FISC_UND,DEBITO_CORP_UND,CREDITO_CORP_UND,RecordDate,CreatedBy,UpdatedBy,CreateDate)

																VALUES
																(@TEMP_CENTRO_COSTO,@TEMP_CUENTA_CONTABLE,@TEMP_FECHA,@TEMP_SALDO_FISC_LOCAL_S,@TEMP_SALDO_FISC_DOLAR_S,@TEMP_SALDO_CORP_LOCAL_S
																,@TEMP_SALDO_CORP_DOLAR_S,@TEMP_DEBITO_FISC_LOCAL_S,@TEMP_CREDITO_FISC_LOCAL_S,@TEMP_DEBITO_CORP_LOCAL_S,@TEMP_CREDITO_CORP_LOCAL_S
																,@TEMP_DEBITO_FISC_DOLAR_S,@TEMP_CREDITO_FISC_DOLAR_S,@TEMP_DEBITO_CORP_DOLAR_S,@TEMP_CREDITO_CORP_DOLAR_S,@TEMP_SALDO_FISC_UND_S
																,@TEMP_SALDO_CORP_UND_S,@TEMP_DEBITO_FISC_UND_S,@TEMP_CREDITO_FISC_UND_S,@TEMP_DEBITO_CORP_UND_S
																,@TEMP_CREDITO_CORP_UND_S,GETDATE(),@TEMP_CreatedBy,@TEMP_UpdatedBy,GETDATE())

																UPDATE AHPF_HN.ASHPF.SALDO
																SET SALDO_FISC_LOCAL	=	SALDO_FISC_LOCAL	- @TEMP_DEBITO_LOCAL,
																DEBITO_FISC_LOCAL		=	DEBITO_FISC_LOCAL	+ @TEMP_DEBITO_LOCAL

																WHERE 
																CENTRO_COSTO		=	@TEMP_CENTRO_COSTO_S		AND
																CUENTA_CONTABLE		=	@TEMP_CUENTA_CONTABLE_S		AND
																FECHA				=	@TEMP_FECHA_S


															
															END	


												END

												-----------------------------------------------------------------------------------------
												------------------------- PERIODO CONTABLE EXISTE	-------------------------------------
												-----------------------------------------------------------------------------------------

												IF @PERIODO_ESTADO > 0
												BEGIN
													
																IF @TEMP_TIPO	=	'C'
																BEGIN		
																	UPDATE AHPF_HN.ASHPF.SALDO
																	SET SALDO_FISC_LOCAL	=	SALDO_FISC_LOCAL	+ @TEMP_CREDITO_LOCAL,
																	CREDITO_FISC_LOCAL		=	CREDITO_FISC_LOCAL	+ @TEMP_CREDITO_LOCAL

																	WHERE 
																	CENTRO_COSTO		=	@TEMP_CENTRO_COSTO_S		AND
																	CUENTA_CONTABLE		=	@TEMP_CUENTA_CONTABLE_S		AND
																	FECHA				=	@TEMP_FECHA_S
																END

																IF @TEMP_TIPO	=	'D'
																BEGIN
																	UPDATE AHPF_HN.ASHPF.SALDO
																	SET SALDO_FISC_LOCAL	=	SALDO_FISC_LOCAL	- @TEMP_DEBITO_LOCAL,
																	DEBITO_FISC_LOCAL		=	DEBITO_FISC_LOCAL	+ @TEMP_DEBITO_LOCAL

																	WHERE 
																	CENTRO_COSTO		=	@TEMP_CENTRO_COSTO_S		AND
																	CUENTA_CONTABLE		=	@TEMP_CUENTA_CONTABLE_S		AND
																	FECHA				=	@TEMP_FECHA_S
																END
												END

								SET @A = @A + 1
							END

							

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END
			EXECUTE ASHPF.Sp_LogError;
	END CATCH;
END
GO


