-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE ASHPF.sP_COMMIT_SEGMENT_COST 
	-- Add the parameters for the stored procedure here
	
	@FACTURA			AS VARCHAR(50),
	@ARTICULO			AS VARCHAR(20),
	@Id_UH				AS VARCHAR(20)	

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @CONDICION_PAGO		AS VARCHAR(4)
	DECLARE @TIPO				AS VARCHAR(1)
	DECLARE @TIPO_ARTICULO		AS VARCHAR(1)
	DECLARE @ARTICULO_CUENTA	AS VARCHAR(40)
	
    -- Insert statements for procedure here
	BEGIN TRY
		BEGIN TRANSACTION

			SET @CONDICION_PAGO			= (SELECT F.CONDICION_PAGO FROM PRUEBA.ASHPF.FACTURA AS F WHERE F.FACTURA = @FACTURA)
			SET @TIPO_ARTICULO			= (SELECT A.TIPO FROM PRUEBA.ASHPF.ARTICULO AS A WHERE A.ARTICULO = @ARTICULO)
			SET @ARTICULO_CUENTA		= (SELECT A.ARTICULO_CUENTA FROM PRUEBA.ASHPF.ARTICULO AS A WHERE A.ARTICULO = @ARTICULO)
	

			--- ARTICULO TERMINADO 	
				
				IF(@TIPO_ARTICULO = 'T')
				BEGIN

					--COSTO DE INVENTARIO 

					SELECT TC.C_COSTO_INVENTARIO AS CENTRO_COSTO, AC.CTA_INVENTARIO, ('FAC#' + FL.FACTURA + ' - ' + F.CLIENTE) AS FUENTE,
					('FAC#' + FL.FACTURA + ' - ' + F.CLIENTE + ' - ' + F.NOMBRE_CLIENTE) AS REFERENCIA,FL.COSTO_TOTAL AS CREDITO
					FROM PRUEBA.ASHPF.FACTURA_LINEA AS FL
								INNER JOIN PRUEBA.ASHPF.FACTURA  AS F ON F.FACTURA  = FL.FACTURA
								INNER JOIN PRUEBA.ASHPF.ARTICULO AS A ON A.ARTICULO = FL.ARTICULO 
								INNER JOIN  H1_ASHONPLAFA_387.dbo.UT_CC AS TC ON TC.ARTICULO_CUENTA COLLATE SQL_Latin1_General_CP850_CI_AS = A.ARTICULO_CUENTA 
								INNER JOIN H1_ASHONPLAFA_387.dbo.UT_CCA AS AC ON AC.ARTICULO_CUENTA = TC.ARTICULO_CUENTA


					WHERE FL.FACTURA=@FACTURA AND  TC.ARTICULO_CUENTA=@ARTICULO_CUENTA AND TC.Id_UH=@Id_UH AND FL.ANULADA='N'

					--COSTO DE VENTA 

					SELECT TC.C_COSTO_VENTA AS CENTRO_COSTO, AC.CTA_VENTAS_LOC,('FAC#' + FL.FACTURA + ' - ' + F.CLIENTE) AS FUENTE,
					('FAC#' + FL.FACTURA + ' - ' + F.CLIENTE + ' - ' + F.NOMBRE_CLIENTE) AS REFERENCIA, FL.PRECIO_TOTAL AS CREDITO

					FROM PRUEBA.ASHPF.FACTURA_LINEA AS FL
								INNER JOIN PRUEBA.ASHPF.FACTURA  AS F ON F.FACTURA  = FL.FACTURA
								INNER JOIN PRUEBA.ASHPF.ARTICULO AS A ON A.ARTICULO = FL.ARTICULO 
								INNER JOIN  H1_ASHONPLAFA_387.dbo.UT_CC AS TC ON TC.ARTICULO_CUENTA COLLATE SQL_Latin1_General_CP850_CI_AS = A.ARTICULO_CUENTA 
								INNER JOIN H1_ASHONPLAFA_387.dbo.UT_CCA AS AC ON AC.ARTICULO_CUENTA = TC.ARTICULO_CUENTA


					WHERE FL.FACTURA=@FACTURA AND  TC.ARTICULO_CUENTA=@ARTICULO_CUENTA AND TC.Id_UH=@Id_UH AND FL.ANULADA='N'
				END
				ELSE
				BEGIN
						IF(@TIPO_ARTICULO = 'V')
							SELECT TC.C_COSTO_VENTA AS CENTRO_COSTO, AC.CTA_VENTAS_LOC, AD.DESCRIPCION, ('FAC#' + FL.FACTURA + ' - ' + F.CLIENTE) AS FUENTE,
							('FAC#' + FL.FACTURA + ' - ' + F.CLIENTE + ' - ' + F.NOMBRE_CLIENTE) AS REFERENCIA,FL.PRECIO_TOTAL AS CREDITO
							FROM PRUEBA.ASHPF.FACTURA_LINEA AS FL
										INNER JOIN PRUEBA.ASHPF.FACTURA  AS F ON F.FACTURA  = FL.FACTURA
										INNER JOIN PRUEBA.ASHPF.ARTICULO AS A ON A.ARTICULO = FL.ARTICULO 
										INNER JOIN  H1_ASHONPLAFA_387.dbo.UT_CC AS TC ON TC.ARTICULO_CUENTA COLLATE SQL_Latin1_General_CP850_CI_AS = A.ARTICULO_CUENTA 
										INNER JOIN H1_ASHONPLAFA_387.dbo.UT_CCA AS AC ON AC.ARTICULO_CUENTA = TC.ARTICULO_CUENTA
										INNER JOIN PRUEBA.ASHPF.ARTICULO_CUENTA AS AD ON AD.ARTICULO_CUENTA = TC.ARTICULO_CUENTA COLLATE SQL_Latin1_General_CP1_CI_AS
										WHERE FL.FACTURA=@FACTURA AND  TC.ARTICULO_CUENTA=@ARTICULO_CUENTA AND TC.Id_UH=@Id_UH	AND FL.ANULADA='N'		
				END
		
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END
			EXECUTE ASHPF.Sp_LogError;

	END CATCH;

END
GO


EXEC ASHPF.sP_COMMIT_SEGMENT_COST  '000-004-01-00097460', '4255-2544','0801'
EXEC ASHPF.sP_COMMIT_SEGMENT_COST '000-004-01-00097460','4374-7836',  '0801'

--SELECT * FROM dbo.ErrorLog