USE [PRUEBA]
GO

/****** Object:  StoredProcedure [ASHPF].[sP_PEDIDO_OV_H1]    Script Date: 22/11/2016 10:47:14 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Jose Rivera
-- Create date: 09/11/2016
-- Description:	Insert Sales Order Header Softland ERP
-- =============================================
CREATE PROCEDURE [ASHPF].[sP_PEDIDO_OV_H1] 
	-- Add the parameters for the stored procedure here
	@Id_OV AS INT
	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.

	------ SalesOrder Header

		DECLARE	@PEDIDO				AS VARCHAR(20) 
		DECLARE @ESTADO				AS VARCHAR(1)		='N'
		DECLARE @FECHA_PEDIDO		AS DATE				
		DECLARE @FECHA_PROMETIDA	AS DATE				
		DECLARE @FECHA_PROX_EMBARQU	AS DATE				
		DECLARE @EMBARCAR_A			AS VARCHAR(80)
		DECLARE @DIREC_EMBARQUE		AS VARCHAR(8)
		DECLARE @TOTAL_MERCADERIA	AS DECIMAL(28,8)
		DECLARE @MONTO_ANTICIPO		AS DECIMAL(28,8)	=0
		DECLARE @MONTO_FLETE		AS DECIMAL(28,8)	=0
		DECLARE @MONTO_SEGURO		AS DECIMAL(28,8)	=0
		DECLARE @MONTO_DOCUMENTACIO	AS DECIMAL(28,8)	=0
		DECLARE @TIPO_DESCUENTO1	AS VARCHAR(1)		='P'
		DECLARE @TIPO_DESCUENTO2	AS VARCHAR(1)		='P'
		DECLARE @MONTO_DESCUENTO1	AS DECIMAL(28,8)	=0
		DECLARE @MONTO_DESCUENTO2	AS DECIMAL(28,8)	=0
		DECLARE @PORC_DESCUENTO1	AS DECIMAL(28,8)	=0
		DECLARE @PORC_DESCUENTO2	AS DECIMAL(28,8)	=0
		DECLARE @TOTAL_IMPUESTO1	AS DECIMAL(28,8)	=0
		DECLARE @TOTAL_IMPUESTO2	AS DECIMAL(28,8)	=0
		DECLARE	@TOTAL_A_FACTURAR	AS DECIMAL(28,8)
		DECLARE @PORC_COMI_VENDEDOR	AS DECIMAL(28,8)	=0
		DECLARE @PORC_COMI_COBRADOR	AS DECIMAL(28,8)	=0
		DECLARE @TOTAL_CANCELADO	AS DECIMAL(28,8)	=0
		DECLARE @TOTAL_UNIDADES		AS DECIMAL(28,8)
		DECLARE	@IMPRESO			AS VARCHAR(1)		='N'
		DECLARE	@FECHA_HORA			AS DATE
		DECLARE @DESCUENTO_VOLUMEN	AS DECIMAL(28,8)	=0
		DECLARE @TIPO_PEDIDO		AS VARCHAR(1)		='N'
		DECLARE	@MONEDA_PEDIDO		AS VARCHAR(1)
		DECLARE @VERSION_NP			AS INT	
		DECLARE	@AUTORIZADO			AS VARCHAR(1)		='N'
		DECLARE	@DOC_A_GENERAR		AS VARCHAR(1)		='F'
		DECLARE	@CLASE_PEDIDO		AS VARCHAR(1)		='N'
		DECLARE @MONEDA				AS VARCHAR(1)
		DECLARE	@NIVEL_PRECIO		AS VARCHAR(12)
		DECLARE	@COBRADOR			AS VARCHAR(4)
		DECLARE	@RUTA				AS VARCHAR(4)
		DECLARE	@USUARIO			AS VARCHAR(25)
		DECLARE	@CONDICION_PAGO		AS VARCHAR(4)
		DECLARE	@BODEGA				AS VARCHAR(4)
		DECLARE	@ZONA				AS VARCHAR(4)
		DECLARE	@VENDEDOR			AS VARCHAR(4)		='ND'
		DECLARE	@CLIENTE			AS VARCHAR(20)
		DECLARE	@CLIENTE_DIRECCION	AS VARCHAR(20)
		DECLARE	@CLIENTE_CORPORAC	AS VARCHAR(20)
		DECLARE	@CLIENTE_ORIGEN		AS VARCHAR(20)
		DECLARE	@PAIS				AS VARCHAR(4)
		DECLARE	@BACKORDER			AS VARCHAR(1)		='N'
		DECLARE	@DESCUENTO_CASCADA	AS VARCHAR(1)		='N'
		DECLARE	@DIRECCION_FACTURA	AS VARCHAR(4000) 
		DECLARE	@FIJAR_TIPO_CAMBIO	AS VARCHAR(1)		='N'
		DECLARE	@ORIGEN_PEDIDO		AS VARCHAR(1)		='F'
		DECLARE	@TIPO_DOCUMENTO		AS VARCHAR(1)		='P'
		DECLARE @SUBTIPO_DOC_CXC	AS SMALLINT			=0
		DECLARE @TIPO_DOC_CXC		AS VARCHAR(3)		='FAC'
		----------- END ------------
		DECLARE @FLAG				AS INT
		DECLARE @Id_PT				AS	VARCHAR(20)
		DECLARE @SerieOV			INT
		DECLARE @FLAG_PEDIDO		AS VARCHAR(30)

	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRANSACTION;
	
					----------- Fetch New Sales Order ID ----------
						SET @SerieOV= (SELECT SerieOV FROM H1_ASHONPLAFA_385.dbo.US AS U
										   LEFT JOIN H1_ASHONPLAFA_385.dbo.OV AS OV ON
													OV.Id_US = U.Id_US WHERE OV.Id_OV = @Id_OV )
					--- Call sP ASHPF.sPGetSerieOVERP ---
						DECLARE @SerieO AS NVARCHAR(10);
						EXECUTE  ASHPF.sPGetSerieOVERP @SerieOV, @SerieOUT = @SerieO OUTPUT;
				
					--------- END ---------------
					
					 					
					----------- Fetch Id_OV and Id_PT  ----------
								SET @FLAG_PEDIDO	=@SerieO
								SET @FLAG			=(SELECT Id_OV FROM H1_ASHONPLAFA_385.dbo.OV WHERE Id_OV = @Id_OV) 
								SET @Id_PT			=(SELECT Id_PT FROM H1_ASHONPLAFA_385.dbo.OV WHERE Id_OV = @Id_OV)
	

					--- Fetch data from OV and OVAR 
								SELECT 
									 @PEDIDO = @FLAG_PEDIDO,@ESTADO='N',@FECHA_PEDIDO =P.Fecha,@FECHA_PROMETIDA =P.Fecha 
									,@FECHA_PROX_EMBARQU =P.Fecha,@EMBARCAR_A =C1.NOMBRE,@DIREC_EMBARQUE =DE.DIRECCION,@TOTAL_MERCADERIA =(P.Cantidad * ISNULL(AP.PRECIO,0))
									,@MONTO_ANTICIPO =0,@MONTO_FLETE =0,@MONTO_SEGURO =0,@MONTO_DOCUMENTACIO =0,@TIPO_DESCUENTO1 ='P',@TIPO_DESCUENTO2 ='P'
									,@MONTO_DESCUENTO1 =0,@MONTO_DESCUENTO2 =0,@PORC_DESCUENTO1 =0,@PORC_DESCUENTO2 =0,@TOTAL_IMPUESTO1 =0,@TOTAL_IMPUESTO2 =0
									,@TOTAL_A_FACTURAR =(P.Cantidad * ISNULL(AP.PRECIO,0)),@PORC_COMI_VENDEDOR =0,@PORC_COMI_COBRADOR =0,@TOTAL_CANCELADO =0
									,@TOTAL_UNIDADES =0,@IMPRESO ='N',@FECHA_HORA =P.Fecha,@DESCUENTO_VOLUMEN =0,@TIPO_PEDIDO ='N',@MONEDA_PEDIDO =NP.MONEDA 
									,@VERSION_NP =AP.VERSION_ARTICULO,@AUTORIZADO ='N',@DOC_A_GENERAR ='F',@CLASE_PEDIDO ='N',@MONEDA =NP.MONEDA 
									,@NIVEL_PRECIO =NP.NIVEL_PRECIO,@COBRADOR =C.Referencia1,@RUTA =C1.RUTA,@USUARIO =P.Usuario_Registro,@CONDICION_PAGO =C1.CONDICION_PAGO
									,@BODEGA =CO.Almacen,@ZONA =C1.ZONA,@VENDEDOR ='ND',@CLIENTE =P.Id_PT,@CLIENTE_DIRECCION =P.Id_PT,@CLIENTE_CORPORAC =P.Id_PT 
									,@CLIENTE_ORIGEN =P.Id_PT,@PAIS =C1.PAIS,@SUBTIPO_DOC_CXC =0,@TIPO_DOC_CXC ='FAC',@BACKORDER ='N',@DESCUENTO_CASCADA ='N' 
									,@DIRECCION_FACTURA =DE.DIRECCION,@FIJAR_TIPO_CAMBIO ='N',@ORIGEN_PEDIDO ='F',@TIPO_DOCUMENTO ='P'  
															
									FROM H1_ASHONPLAFA_385.dbo.OV AS P
											INNER JOIN PRUEBA.ASHPF.CLIENTE			AS C1 ON C1.CLIENTE = P.Id_PT COLLATE SQL_Latin1_General_CP850_CI_AS
											LEFT JOIN H1_ASHONPLAFA_385.dbo.US		AS CO ON CO.Id_US = P.Id_US
											LEFT JOIN PRUEBA.ASHPF.NIVEL_PRECIO		AS NP ON NP.Id_NIVEL_PRECIO = P.Id_LP
											LEFT JOIN PRUEBA.ASHPF.ARTICULO_PRECIO	AS AP ON AP.ARTICULO = P.Id_AR COLLATE SQL_Latin1_General_CP850_CI_AS AND AP.NIVEL_PRECIO = NP.NIVEL_PRECIO
											LEFT JOIN H1_ASHONPLAFA_385.dbo.PR		AS C  ON C.Id_PR = P.Id_PR
											LEFT JOIN PRUEBA.ASHPF.DIRECC_EMBARQUE	AS DE ON DE.CLIENTE = P.Id_PT COLLATE SQL_Latin1_General_CP850_CI_AS

									WHERE   P.Id_PT = @Id_PT AND P.Id_OV = @FLAG
		
						---------- INSERT Sales Orde Header in ERP ---------

									INSERT INTO ASHPF.PEDIDO
									(PEDIDO,ESTADO,FECHA_PEDIDO,FECHA_PROMETIDA,FECHA_PROX_EMBARQU,EMBARCAR_A,DIREC_EMBARQUE,TOTAL_MERCADERIA,MONTO_ANTICIPO,MONTO_FLETE,
									MONTO_SEGURO,MONTO_DOCUMENTACIO,TIPO_DESCUENTO1,TIPO_DESCUENTO2,MONTO_DESCUENTO1,MONTO_DESCUENTO2,PORC_DESCUENTO1,PORC_DESCUENTO2,TOTAL_IMPUESTO1,TOTAL_IMPUESTO2,
									TOTAL_A_FACTURAR,PORC_COMI_VENDEDOR,PORC_COMI_COBRADOR,TOTAL_CANCELADO,TOTAL_UNIDADES,IMPRESO,FECHA_HORA,DESCUENTO_VOLUMEN,TIPO_PEDIDO,MONEDA_PEDIDO,VERSION_NP,
									AUTORIZADO,DOC_A_GENERAR,CLASE_PEDIDO,MONEDA,NIVEL_PRECIO,COBRADOR,RUTA,USUARIO,CONDICION_PAGO,BODEGA,
									ZONA,VENDEDOR,CLIENTE,CLIENTE_DIRECCION,CLIENTE_CORPORAC,CLIENTE_ORIGEN,PAIS,SUBTIPO_DOC_CXC,TIPO_DOC_CXC,BACKORDER,DESCUENTO_CASCADA,DIRECCION_FACTURA,
									FIJAR_TIPO_CAMBIO,ORIGEN_PEDIDO,TIPO_DOCUMENTO)
									VALUES
									(@FLAG_PEDIDO,@ESTADO,@FECHA_PEDIDO,@FECHA_PROMETIDA,@FECHA_PROX_EMBARQU,@EMBARCAR_A,@DIREC_EMBARQUE,@TOTAL_MERCADERIA,@MONTO_ANTICIPO,@MONTO_FLETE,
									@MONTO_SEGURO,@MONTO_DOCUMENTACIO,@TIPO_DESCUENTO1,@TIPO_DESCUENTO2,@MONTO_DESCUENTO1,@MONTO_DESCUENTO2,@PORC_DESCUENTO1,@PORC_DESCUENTO2,@TOTAL_IMPUESTO1,@TOTAL_IMPUESTO2,
									@TOTAL_A_FACTURAR,@PORC_COMI_VENDEDOR,@PORC_COMI_COBRADOR,@TOTAL_CANCELADO,@TOTAL_UNIDADES,@IMPRESO,@FECHA_HORA,@DESCUENTO_VOLUMEN,@TIPO_PEDIDO,@MONEDA_PEDIDO,
									@VERSION_NP,@AUTORIZADO,@DOC_A_GENERAR,@CLASE_PEDIDO,@MONEDA,@NIVEL_PRECIO,@COBRADOR,@RUTA,@USUARIO,@CONDICION_PAGO,@BODEGA,
									@ZONA,@VENDEDOR,@CLIENTE,@CLIENTE_DIRECCION,@CLIENTE_CORPORAC,@CLIENTE_ORIGEN,@PAIS,@SUBTIPO_DOC_CXC,@TIPO_DOC_CXC,@BACKORDER,@DESCUENTO_CASCADA,@DIRECCION_FACTURA,
									@FIJAR_TIPO_CAMBIO,@ORIGEN_PEDIDO,@TIPO_DOCUMENTO)

						---------- END ----------

						---------- Call Procedure ----------

												-- Scannig Sales Order Lines --
												EXEC  ASHPF.sP_PEDIDO_LINEA_OV_H1 @FLAG, @FLAG_PEDIDO

												EXEC ASHPF.sP_AUDIT_TRANS_INV_H1 @USUARIO,@FECHA_HORA,@FECHA_PEDIDO,@CLIENTE,@PEDIDO

												-- Update Total Due SalesOrderHeader --

												EXEC  ASHPF.sPSOHTotalDue_Update @FLAG_PEDIDO

												-- Extract and load Sales Order Header to FC --

												EXEC  ASHPF.sP_PEDIDO_OV_FC @FLAG, @Id_PT

												-- Extract and load Sales Order Header to FCDT --

												EXEC ASHPF.sP_PEDIDO_LINEA_OV_FCDT @FLAG

												-------- AND --------
			


			COMMIT TRANSACTION
		END TRY 
		BEGIN CATCH

			IF @@TRANCOUNT > 0
			BEGIN 
				ROLLBACK TRANSACTION;
			END
				EXECUTE ASHPF.Sp_LogError;
		END CATCH;

END

GO


