USE [PRUEBA]
GO

/****** Object:  StoredProcedure [ASHPF].[sP_PEDIDO_LINEA_AD_H1]    Script Date: 22/11/2016 10:46:13 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Jose rivera	
-- Create date: 18/11/2016
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [ASHPF].[sP_PEDIDO_LINEA_AD_H1]
	-- Add the parameters for the stored procedure here
	@Id_AD				AS INT, 
	@FLAG_PEDIDO		AS VARCHAR(30)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.

		DECLARE @FLAG				AS INT 
		DECLARE @Id_PT				AS	VARCHAR
		DECLARE	@PEDIDO				AS VARCHAR(20)
		DECLARE	@PEDIDO_LINEA		AS SMALLINT 
		DECLARE @ARTICULO			AS VARCHAR(20)
		DECLARE @FECHA_ENTREGA		AS DATE
		DECLARE	@LINEA_USUARIO		AS SMALLINT
		DECLARE	@PRECIO_UNITARIO	AS DECIMAL(28,8)
		DECLARE	@CANTIDAD_PEDIDA	AS DECIMAL(28,8)
		DECLARE	@CANTIDAD_A_FACTURA	AS DECIMAL(28,8)
		DECLARE	@CANTIDAD_FACTURADA	AS DECIMAL(28,8)
		DECLARE @CANTIDAD_RESERVADA	AS DECIMAL(28,8)
		DECLARE @CANTIDAD_BONIFICAD	AS DECIMAL(28,8)
		DECLARE @CANTIDAD_CANCELADA	AS DECIMAL(28,8)
		DECLARE @TIPO_DESCUENTO		AS VARCHAR(1)
		DECLARE @MONTO_DESCUENTO	AS DECIMAL(28,8)
		DECLARE @PORC_DESCUENTO		AS DECIMAL(28,8)
		DECLARE	@BODEGA				AS VARCHAR(4)
		DECLARE @LOTE				AS VARCHAR(15)
        DECLARE @LOCALIZACION		AS VARCHAR(8)
		DECLARE @ESTADO				AS VARCHAR(1)		
		DECLARE @FECHA_PROMETIDA	AS DATE
		DECLARE @CENTRO_COSTO		AS VARCHAR(25)
        DECLARE @CUENTA_CONTABLE	AS VARCHAR(25)
		DECLARE @COUNT_LINEA		AS INT

	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRANSACTION;

		
    -- Insert statements for procedure here

		DECLARE SELECT_AD CURSOR LOCAL
		FOR

				SELECT @FLAG_PEDIDO,AD.Id_AD,SR.Id_AR,'N',AD.Fecha_Registro,AD.Id_AD,SA.Id_AL,NULL,NULL,V3.UnitPrice,SR.Cantidad,SR.Cantidad,SR.Cantidad,0,0,0,
					'P',0.00000000,0.00000000,AD.Fecha_Registro,
						(SELECT CTR.CENTRO_COSTO FROM   PRUEBA.ASHPF.CENTRO_COSTO	AS	CTR	WHERE  CTR.CENTRO_COSTO	=	
						(SELECT CASE WHEN C.LOCAL = 'L' THEN AC.CTR_VENTAS_LOC  ELSE AC.CTR_VENTAS_EXP END 
							FROM   PRUEBA.ASHPF.CLIENTE C, PRUEBA.ASHPF.ARTICULO_CUENTA AC, PRUEBA.ASHPF.ARTICULO A 
							WHERE  C.CLIENTE = AD.Id_PT COLLATE SQL_Latin1_General_CP850_CI_AS  
							AND A.ARTICULO = SR.Id_AR	COLLATE SQL_Latin1_General_CP850_CI_AS  
							AND A.ARTICULO_CUENTA = AC.ARTICULO_CUENTA)),
						(SELECT CTA.CUENTA_CONTABLE	FROM   PRUEBA.ASHPF.CUENTA_CONTABLE	AS	CTA	WHERE  CTA.CUENTA_CONTABLE =
						(SELECT CASE WHEN C.LOCAL = 'L' THEN AC.CTA_VENTAS_LOC ELSE AC.CTA_VENTAS_EXP  END 
							FROM	PRUEBA.ASHPF.CLIENTE C, PRUEBA.ASHPF.ARTICULO_CUENTA AC, PRUEBA.ASHPF.ARTICULO A 
							WHERE  C.CLIENTE = AD.Id_PT COLLATE SQL_Latin1_General_CP850_CI_AS 
							AND A.ARTICULO = SA.Id_AR	COLLATE SQL_Latin1_General_CP850_CI_AS
							AND A.ARTICULO_CUENTA = AC.ARTICULO_CUENTA))

				FROM H1_ASHONPLAFA_385.dbo.AD AS AD
						LEFT JOIN H1_ASHONPLAFA_385.dbo.ADHB	AS AH	ON AH.Id_AD = AD.Id_AD
						LEFT JOIN H1_ASHONPLAFA_385.dbo.SL		AS S	ON S.Id_ADHB = AH.Id_ADHB
						LEFT JOIN H1_ASHONPLAFA_385.dbo.SLAR	AS SR	ON SR.Id_SL = S.Id_SL
						LEFT JOIN H1_ASHONPLAFA_385.dbo.V_SLARALLT AS SA ON SA.Id_SL = S.Id_SL
						LEFT JOIN H1_ASHONPLAFA_385.dbo.V_ITPR AS V3 ON V3.PriceList = AD.Id_LP AND V3.ItemCode = SR.Id_AR
						LEFT OUTER JOIN H1_ASHONPLAFA_385.dbo.V_SA	AS ST	ON ST.Id_ADHB = AH.Id_ADHB AND ST.Id_AR = SA.Id_AR
						


				WHERE AD.Id_AD=@Id_AD	AND ST.Estatus='PR'

				UNION 


				SELECT @FLAG_PEDIDO,AD1.Id_AD,SA.Id_AR,'N',AD1.Fecha_Registro,AD1.Id_AD,SAL.Id_AL,SAL.Lote,V4.BinCode,V3.UnitPrice,SA.Cantidad,SA.Cantidad,SA.Cantidad,0,0,0,
						'P',0.00000000,0.00000000,AD1.Fecha_Registro,
						(SELECT CTR.CENTRO_COSTO FROM   PRUEBA.ASHPF.CENTRO_COSTO	AS	CTR	WHERE  CTR.CENTRO_COSTO	=	
						(SELECT CASE WHEN C.LOCAL = 'L' THEN AC.CTR_VENTAS_LOC  ELSE AC.CTR_VENTAS_EXP END 
							FROM   PRUEBA.ASHPF.CLIENTE C, PRUEBA.ASHPF.ARTICULO_CUENTA AC, PRUEBA.ASHPF.ARTICULO A 
							WHERE  C.CLIENTE = AD1.Id_PT COLLATE SQL_Latin1_General_CP850_CI_AS  
							AND A.ARTICULO = SA.Id_AR	COLLATE SQL_Latin1_General_CP850_CI_AS  
							AND A.ARTICULO_CUENTA = AC.ARTICULO_CUENTA)),
						(SELECT CTA.CUENTA_CONTABLE	FROM   PRUEBA.ASHPF.CUENTA_CONTABLE	AS	CTA	WHERE  CTA.CUENTA_CONTABLE =
						(SELECT CASE WHEN C.LOCAL = 'L' THEN AC.CTA_VENTAS_LOC ELSE AC.CTA_VENTAS_EXP  END 
							FROM	PRUEBA.ASHPF.CLIENTE C, PRUEBA.ASHPF.ARTICULO_CUENTA AC, PRUEBA.ASHPF.ARTICULO A 
							WHERE  C.CLIENTE = AD1.Id_PT COLLATE SQL_Latin1_General_CP850_CI_AS 
							AND A.ARTICULO = SA.Id_AR	COLLATE SQL_Latin1_General_CP850_CI_AS
							AND A.ARTICULO_CUENTA = AC.ARTICULO_CUENTA))

				FROM H1_ASHONPLAFA_385.dbo.AD AS AD1
						LEFT JOIN H1_ASHONPLAFA_385.dbo.ADHB		AS AH	ON AH.Id_AD = AD1.Id_AD
						LEFT JOIN H1_ASHONPLAFA_385.dbo.SA					ON SA.Id_ADHB = AH.Id_ADHB
						LEFT JOIN H1_ASHONPLAFA_385.dbo.SAALLT		AS SAL	ON SAL.Id_SA = SA.Id_SA
						LEFT JOIN H1_ASHONPLAFA_385.dbo.SL			AS S	ON S.Id_ADHB = AH.Id_ADHB
						LEFT JOIN H1_ASHONPLAFA_385.dbo.SLAR		AS SR	ON SR.Id_SL = S.Id_SL
						LEFT JOIN H1_ASHONPLAFA_385.dbo.V_ITPR		AS V3	ON V3.PriceList = AD1.Id_LP AND V3.ItemCode = SA.Id_AR
						LEFT JOIN H1_ASHONPLAFA_385.dbo.V_ITBT		AS V4	ON V4.ItemCode = SA.Id_AR AND V4.WarehouseCode = SAL.Id_AL AND V4.BatchCode = SAL.Lote
						LEFT OUTER JOIN H1_ASHONPLAFA_385.dbo.V_SA	AS ST	ON ST.Id_ADHB = AH.Id_ADHB AND ST.Id_AR = SA.Id_AR
	


				WHERE AD1.Id_AD=@Id_AD AND ST.Estatus='PR'

		OPEN SELECT_AD

		FETCH SELECT_AD INTO @PEDIDO, @COUNT_LINEA,@ARTICULO, @ESTADO, @FECHA_ENTREGA, @COUNT_LINEA, @BODEGA,@LOTE,@LOCALIZACION, @PRECIO_UNITARIO, 
							 @CANTIDAD_PEDIDA, @CANTIDAD_A_FACTURA, @CANTIDAD_FACTURADA, @CANTIDAD_RESERVADA, @CANTIDAD_BONIFICAD, @CANTIDAD_CANCELADA, 
							 @TIPO_DESCUENTO, @MONTO_DESCUENTO, @PORC_DESCUENTO,@FECHA_PROMETIDA,@CENTRO_COSTO,@CUENTA_CONTABLE
		
		WHILE (@@FETCH_STATUS = 0)
		BEGIN;
				
					SELECT @COUNT_LINEA = ISNULL(MAX(ISNULL(PEDIDO_LINEA ,0)) ,0)+1 
					FROM   PRUEBA.ASHPF.PEDIDO_LINEA
					WHERE  PEDIDO = @FLAG_PEDIDO

					INSERT INTO PRUEBA.ASHPF.PEDIDO_LINEA
						(PEDIDO,PEDIDO_LINEA,ARTICULO,ESTADO,FECHA_ENTREGA,LINEA_USUARIO,BODEGA,LOTE,LOCALIZACION,PRECIO_UNITARIO,
						 CANTIDAD_PEDIDA,CANTIDAD_A_FACTURA,CANTIDAD_FACTURADA,CANTIDAD_RESERVADA,CANTIDAD_BONIFICAD,CANTIDAD_CANCELADA,
						 TIPO_DESCUENTO,MONTO_DESCUENTO,PORC_DESCUENTO,FECHA_PROMETIDA,CENTRO_COSTO,CUENTA_CONTABLE)

					VALUES(@FLAG_PEDIDO,@COUNT_LINEA,@ARTICULO,@ESTADO,@FECHA_ENTREGA,@COUNT_LINEA,@BODEGA,@LOTE,@LOCALIZACION,@PRECIO_UNITARIO,
						   @CANTIDAD_PEDIDA,@CANTIDAD_A_FACTURA,@CANTIDAD_FACTURADA,@CANTIDAD_RESERVADA,@CANTIDAD_BONIFICAD,@CANTIDAD_CANCELADA,
						   @TIPO_DESCUENTO,@MONTO_DESCUENTO,@PORC_DESCUENTO,@FECHA_PROMETIDA,@CENTRO_COSTO,@CUENTA_CONTABLE)

						   EXEC ASHPF.EB_EL_H1 @ARTICULO, @CANTIDAD_FACTURADA, @BODEGA, @LOCALIZACION, @LOTE

					FETCH SELECT_AD INTO @PEDIDO, @COUNT_LINEA,@ARTICULO, @ESTADO, @FECHA_ENTREGA, @COUNT_LINEA, @BODEGA,@LOTE,@LOCALIZACION, @PRECIO_UNITARIO, 
										@CANTIDAD_PEDIDA, @CANTIDAD_A_FACTURA, @CANTIDAD_FACTURADA, @CANTIDAD_RESERVADA, @CANTIDAD_BONIFICAD, @CANTIDAD_CANCELADA, 
										@TIPO_DESCUENTO, @MONTO_DESCUENTO, @PORC_DESCUENTO,@FECHA_PROMETIDA,@CENTRO_COSTO,@CUENTA_CONTABLE;
		END;
		CLOSE SELECT_AD
		DEALLOCATE SELECT_AD
		
	COMMIT TRANSACTION
	END TRY
	BEGIN CATCH

		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END
			EXECUTE ASHPF.Sp_LogError;
	END CATCH;			
END

GO


