USE [PRUEBA]
GO

/****** Object:  StoredProcedure [ASHPF].[sP_PEDIDO_LINEA_OV_H1]    Script Date: 22/11/2016 10:46:44 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Jose Rivera
-- Create date: 09/11/2016
-- Description:	Insert Sales Order Details Softland ERP
-- =============================================
CREATE PROCEDURE [ASHPF].[sP_PEDIDO_LINEA_OV_H1]
	-- Add the parameters for the stored procedure here
	@Id_OV				AS INT, 
	@FLAG_PEDIDO		AS VARCHAR(30)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.

		
		DECLARE @FLAG				AS INT 
		DECLARE @Id_PT				AS	VARCHAR
		DECLARE	@PEDIDO				AS VARCHAR(20)
		DECLARE	@PEDIDO_LINEA		AS SMALLINT 
		DECLARE @ARTICULO			AS VARCHAR(20)
		DECLARE @FECHA_ENTREGA		AS DATE
		DECLARE	@LINEA_USUARIO		AS SMALLINT
		DECLARE	@PRECIO_UNITARIO	AS DECIMAL(28,8)
		DECLARE	@CANTIDAD_PEDIDA	AS DECIMAL(28,8)
		DECLARE	@CANTIDAD_A_FACTURA	AS DECIMAL(28,8)
		DECLARE	@CANTIDAD_FACTURADA	AS DECIMAL(28,8)
		DECLARE @CANTIDAD_RESERVADA	AS DECIMAL(28,8)
		DECLARE @CANTIDAD_BONIFICAD	AS DECIMAL(28,8)
		DECLARE @CANTIDAD_CANCELADA	AS DECIMAL(28,8)
		DECLARE @TIPO_DESCUENTO		AS VARCHAR(1)
		DECLARE @MONTO_DESCUENTO	AS DECIMAL(28,8)
		DECLARE @PORC_DESCUENTO		AS DECIMAL(28,8)
		DECLARE	@BODEGA				AS VARCHAR(4)
		DECLARE @LOTE				AS VARCHAR(15)
        DECLARE @LOCALIZACION		AS VARCHAR(8)
		DECLARE @ESTADO				AS VARCHAR(1)		
		DECLARE @FECHA_PROMETIDA	AS DATE
		DECLARE @CENTRO_COSTO		AS VARCHAR(25)
        DECLARE @CUENTA_CONTABLE	AS VARCHAR(25)
		DECLARE @COUNT_LINEA		AS INT
	
		
	
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRANSACTION;

    -- Insert statements for procedure here
				SET @FLAG =(SELECT Id_OV FROM H1_ASHONPLAFA_385.dbo.OV WHERE Id_OV = @Id_OV)  	
				
				DECLARE SELECT_OVAR CURSOR LOCAL
				FOR 

								SELECT @FLAG_PEDIDO,V1.Id_OV,V1.Id_AR,'N',V1.Fecha_Registro,V1.Id_OV,V4.Almacen,V3.UnitPrice,
									V1.Cantidad,V1.Cantidad,V1.Cantidad,V1.Cantidad,V1.Cantidad,V1.Cantidad,'P',0,0,V1.Fecha_Registro	
			
								FROM H1_ASHONPLAFA_385.dbo.OV AS V1 
									LEFT JOIN H1_ASHONPLAFA_385.dbo.V_ITPR AS V3 ON
										V3.PriceList = V1.Id_LP AND V3.ItemCode = V1.Id_AR
									LEFT JOIN H1_ASHONPLAFA_385.dbo.US AS V4 ON
										V4.Id_US = V1.Id_US
									LEFT JOIN H1_ASHONPLAFA_385.dbo.V_ARALLT AS V5 ON
										V5.Id_AL = V4.Almacen AND V5.Id_AR = V1.Id_AR

								WHERE V1.Id_OV=@FLAG

								UNION

								SELECT	@FLAG_PEDIDO,V2.Id_OV,V2.Id_AR,'N',V2.Fecha_Registro,V2.Id_OV, V4.Almacen,V3.UnitPrice
									,V2.Cantidad,V2.Cantidad,V2.Cantidad,V2.Cantidad,V2.Cantidad,V2.Cantidad,'P',0,0,V2.Fecha_Registro		

								FROM H1_ASHONPLAFA_385.dbo.OVAR AS V2 
									LEFT JOIN H1_ASHONPLAFA_385.dbo.OV AS V1 ON V1.Id_OV = V2.Id_OV
									LEFT JOIN H1_ASHONPLAFA_385.dbo.V_ITPR AS V3 ON V3.PriceList = V1.Id_LP AND V3.ItemCode = V2.Id_AR
									LEFT JOIN H1_ASHONPLAFA_385.dbo.US AS V4 ON	V4.Id_US = V1.Id_US
								
								
								WHERE V2.Id_OV =@FLAG
					

				OPEN SELECT_OVAR

				FETCH SELECT_OVAR INTO @PEDIDO, @COUNT_LINEA,@ARTICULO, @ESTADO, @FECHA_ENTREGA, @COUNT_LINEA, @BODEGA, @PRECIO_UNITARIO, 
									   @CANTIDAD_PEDIDA, @CANTIDAD_A_FACTURA, @CANTIDAD_FACTURADA, @CANTIDAD_RESERVADA, @CANTIDAD_BONIFICAD, @CANTIDAD_CANCELADA, 
									   @TIPO_DESCUENTO, @MONTO_DESCUENTO, @PORC_DESCUENTO,@FECHA_PROMETIDA


				WHILE (@@FETCH_STATUS = 0)
				BEGIN;

					SELECT @COUNT_LINEA = ISNULL(MAX(ISNULL(PEDIDO_LINEA ,0)) ,0)+1 
					FROM   PRUEBA.ASHPF.PEDIDO_LINEA
					WHERE  PEDIDO = @FLAG_PEDIDO

					INSERT INTO PRUEBA.ASHPF.PEDIDO_LINEA
						(PEDIDO,PEDIDO_LINEA,ARTICULO,ESTADO,FECHA_ENTREGA,LINEA_USUARIO,BODEGA,PRECIO_UNITARIO,
						 CANTIDAD_PEDIDA,CANTIDAD_A_FACTURA,CANTIDAD_FACTURADA,CANTIDAD_RESERVADA,CANTIDAD_BONIFICAD,CANTIDAD_CANCELADA,
						 TIPO_DESCUENTO,MONTO_DESCUENTO,PORC_DESCUENTO,FECHA_PROMETIDA)

					VALUES(@FLAG_PEDIDO,@COUNT_LINEA,@ARTICULO,@ESTADO,@FECHA_ENTREGA,@COUNT_LINEA,@BODEGA,@PRECIO_UNITARIO,
						   @CANTIDAD_PEDIDA,@CANTIDAD_A_FACTURA,@CANTIDAD_FACTURADA,@CANTIDAD_RESERVADA,@CANTIDAD_BONIFICAD,@CANTIDAD_CANCELADA,
						   @TIPO_DESCUENTO,@MONTO_DESCUENTO,@PORC_DESCUENTO,@FECHA_PROMETIDA)

					FETCH SELECT_OVAR INTO @PEDIDO, @COUNT_LINEA,@ARTICULO, @ESTADO, @FECHA_ENTREGA, @COUNT_LINEA, @BODEGA, @PRECIO_UNITARIO, 
										@CANTIDAD_PEDIDA, @CANTIDAD_A_FACTURA, @CANTIDAD_FACTURADA, @CANTIDAD_RESERVADA, @CANTIDAD_BONIFICAD, @CANTIDAD_CANCELADA, 
										@TIPO_DESCUENTO, @MONTO_DESCUENTO, @PORC_DESCUENTO,@FECHA_PROMETIDA;
				END;
				CLOSE SELECT_OVAR
				DEALLOCATE SELECT_OVAR
				
			COMMIT TRANSACTION
	END TRY
	BEGIN CATCH

		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END
			EXECUTE ASHPF.Sp_LogError;
	END CATCH;			
				
END

GO


