USE [PRUEBA]
GO

/****** Object:  StoredProcedure [ASHPF].[sPSOHTotalDue_Update]    Script Date: 22/11/2016 10:47:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Jose Rivera
-- Create date: 09/11/2016
-- Description:	Update total due Sales Order Header Softland
-- =============================================
CREATE PROCEDURE [ASHPF].[sPSOHTotalDue_Update]
	-- Add the parameters for the stored procedure here
	@FLAG_PEDIDO		AS VARCHAR(30)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @TOTAL_MERCADERIA	AS DECIMAL(28,8)
	DECLARE	@TOTAL_A_FACTURAR	AS DECIMAL(28,8)
	DECLARE @TOTAL_UNIDADES		AS DECIMAL(28,8)

    -- Insert statements for procedure here

	SET @TOTAL_MERCADERIA = (SELECT  SUM(FL.PRECIO_UNITARIO * FL.CANTIDAD_FACTURADA) FROM PRUEBA.ASHPF.PEDIDO_LINEA AS FL WHERE FL.PEDIDO = @FLAG_PEDIDO)
	UPDATE PRUEBA.ASHPF.PEDIDO SET TOTAL_MERCADERIA = @TOTAL_MERCADERIA WHERE PEDIDO = @FLAG_PEDIDO

	SET @TOTAL_A_FACTURAR = (SELECT  SUM(FL.PRECIO_UNITARIO * FL.CANTIDAD_FACTURADA) FROM PRUEBA.ASHPF.PEDIDO_LINEA AS FL WHERE FL.PEDIDO = @FLAG_PEDIDO)
	UPDATE PRUEBA.ASHPF.PEDIDO SET TOTAL_A_FACTURAR =@TOTAL_A_FACTURAR WHERE PEDIDO = @FLAG_PEDIDO

	SET @TOTAL_UNIDADES = (SELECT  SUM(FL.CANTIDAD_FACTURADA) FROM PRUEBA.ASHPF.PEDIDO_LINEA AS FL WHERE FL.PEDIDO = @FLAG_PEDIDO)
	UPDATE PRUEBA.ASHPF.PEDIDO SET TOTAL_UNIDADES = @TOTAL_UNIDADES WHERE PEDIDO = @FLAG_PEDIDO

END



GO


