DECLARE @DATE_FROM	DATETIME
DECLARE @DATE_TO	DATETIME
DECLARE @EXTRACT	VARCHAR(10)

SET @DATE_FROM=(SELECT DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0))
SET @EXTRACT=CONVERT(VARCHAR(8),DATEADD(MONTH,1,@DATE_FROM),112)
SET @DATE_TO=DATEADD(DAY,-1,LEFT(@EXTRACT,6)+'01')

SELECT 

	T0.WddCode,	
	T3.DocNum			'ArOrderNumber',
	CASE
		WHEN T0.OwnerID=T1.[USERID] THEN T1.U_NAME
	END 'Originator',	
	CASE
		WHEN T0.ObjType=17 THEN 'Sales Order'
	END 'Object Type',	
	T3.CardCode				'Customer Code',
	UPPER(T3.CardName)		'Customer Name',
	T0.DocDate,
	CASE 
		WHEN T0.Status='W' THEN 'Pending'
		WHEN T0.Status='Y' THEN	'Approved'
		WHEN T0.Status='N' THEN	'Rejected'
		WHEN T0.Status='P' THEN 'Generated'
		WHEN T0.Status='A' THEN 'Generated by Authorizer'
		WHEN T0.Status='C' THEN 'Canceled'
	END Status_,
	T0.Remarks,
	CASE
		WHEN T0.IsDraft='Y'	THEN 'Yes'
		WHEN T0.IsDraft='N'	THEN 'No'
	END IsDraft,	
	T0.DraftEntry 'ArDraftEntry',	
	CASE
		WHEN T0.ProcesStat='W' THEN 'Pending'
		WHEN T0.ProcesStat='Y' THEN 'Approved'
		WHEN T0.ProcesStat='N' THEN 'Rejected'
		WHEN T0.ProcesStat='P' THEN 'Generated'
		WHEN T0.ProcesStat='A' THEN 'Generated by Authorizer'
		WHEN T0.ProcesStat='C' THEN 'Canceled'
	END ProcesStat_,
	([dbo].[GET_STR_WDD1] (T0.WddCode,20)) STR1,
	ISNULL(CONVERT(VARCHAR(20),([dbo].[GET_STR_DocumentNumber] (T0.DraftEntry))), 'Waiting for approval') STR2


FROM OWDD T0

	INNER  JOIN OUSR T1  ON  T1.[USERID] = T0.[OwnerID]  
	INNER  JOIN OWTM T2  ON  T2.[WtmCode] = T0.[WtmCode]
	INNER  JOIN ODRF T3  ON  T3.DocEntry = T0.DraftEntry

WHERE 

	T0.DocDate >=CONVERT(DATETIME,@DATE_FROM, 112)		AND
	T0.DocDate <=CONVERT(DATETIME,@DATE_TO, 112)		AND
	T0.ObjType=17	
	--AND T0.IsDraft='Y'	
	AND  T0.CurrStep IN (17,20) 


	--SELECT * FROM OWDD WHERE WddCode=5725