

SELECT 

T0.[QUERY_SNB_OBJECTS_ABS_ENTRY_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_WHS_CODE_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_ITEM_CODE_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_SYS_NUMBER_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_DISTINCT_NUMBER_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_ITEM_NAME_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_MNF_SERIAL_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_LOT_NUMBER_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_EXP_DATE_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_STATUS_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_LOCATION_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_QUANTITY_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_COMMIT_QTY_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_COUNT_QTY_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_CCD_NUMBER_RES_ALIAS], 
T0.[QUERY_SNB_OBJECTS_CCD_LINE_NUMBER_RES_ALIAS], 
T1.[ItemCode], 
T1.[SysNumber], 
T1.[DistNumber], 
T1.[MnfSerial], 
T1.[LotNumber], 
T1.[ExpDate], 
T1.[MnfDate], 
T1.[InDate], 
T1.[GrntStart], 
T1.[GrntExp], 
T1.[CreateDate], 
T1.[Location], 
T1.[Status], 
T1.[Notes], 
T1.[DataSource], 
T1.[UserSign], 
T1.[Transfered], 
T1.[Instance], 
T1.[AbsEntry], 
T1.[ObjType], 
T1.[itemName], 
T1.[LogInstanc], 
T1.[UserSign2], 
T1.[UpdateDate], 
T1.[CostTotal], 
T1.[Quantity], 
T1.[QuantOut], 
T1.[PriceDiff], 
T1.[Balance], 
T1.[TrackingNt], 
T1.[TrackiNtLn], 
T1.[SumDec], 
T1.[U_BMM_LOTSTRENGTH], 
T1.[U_BMM_REASONCODE], 
T1.[U_BMM_NOCONTAINER], 
T1.[U_Length], 
T1.[U_Width], 
T1.[U_Guage], 
T1.[U_Roll]


FROM  [dbo].[SNB_8cac7a042dc446abb2fc833e21a6] T0  

	INNER  JOIN [dbo].[OBTN] T1  ON  T1.[AbsEntry] = T0.[QUERY_SNB_OBJECTS_ABS_ENTRY_RES_ALIAS]   

ORDER BY 
T0.[QUERY_SNB_OBJECTS_ITEM_CODE_RES_ALIAS],
T0.[QUERY_SNB_OBJECTS_DISTINCT_NUMBER_RES_ALIAS],
T0.[QUERY_SNB_OBJECTS_WHS_CODE_RES_ALIAS]