--SELECT 

--T0.WddCode,
--T0.DraftEntry												AS 'Draft Key',
--CASE 
--	WHEN T0.ObjType=17 THEN 'Sales Order'
--END DocumentType,
--T1.CardCode,
--T1.CardName,
--(SELECT U_NAME FROM [OUSR] where USERID=T0.OwnerID)			AS 'Originator',
--CASE 
--	WHEN T3.Status='W'	THEN 'Pending'
--	WHEN T3.Status='Y'	THEN 'Approved'
--	WHEN T3.Status='N'	THEN 'Rejected'
--	WHEN T3.Status='P'	THEN 'Generated'
--	WHEN T3.Status='A'	THEN 'Generated by Authorizer'
--	WHEN T3.Status='C'	THEN 'Canceled'
--END Status,
--T0.DocDate,
--T0.Remarks,
--T4.Name														AS 'Stage',
--(SELECT U_NAME FROM [OUSR] where USERID=T3.UserID)			AS 'Draft Updated By',
--T3.UpdateDate												AS 'Draft Updated Date',
--CASE 
--	WHEN T0.ProcesStat='W'	THEN 'Pending'
--	WHEN T0.ProcesStat='Y'	THEN 'Approved'
--	WHEN T0.ProcesStat='N'	THEN 'Rejected'
--	WHEN T0.ProcesStat='P'	THEN 'Generated'
--	WHEN T0.ProcesStat='A'	THEN 'Generated by Authorizer'
--	WHEN T0.ProcesStat='C'	THEN 'Canceled'
--END ProcesStat,
--T0.IsDraft,
--T6.SlpName



--FROM OWDD T0 

--	INNER  JOIN ODRF T1  ON  T1.DocEntry= T0.DraftEntry
--	INNER  JOIN OUSR T2  ON  T2.USERID= T0.OwnerID 
--	LEFT   JOIN WDD1 T3  ON  T3.WddCode=T0.WddCode AND T3.StepCode=20 AND T3.Status='Y'
--	LEFT   JOIN OWST T4  ON  T4.WstCode=T3.StepCode
--	LEFT   JOIN ORDR T5  ON  T5.draftKey=T1.DocEntry
--	LEFT   JOIN OSLP T6  ON  T6.SlpCode=T1.SlpCode

--WHERE 
--T0.ObjType=17		

SELECT * FROM OWDD WHERE WddCode IN (5329,5328,5330,5331)
SELECT * FROM WDD1 WHERE WddCode IN (5329,5328,5330,5331)
--(SELECT U_NAME FROM [OUSR] where USERID=T3.UserID)			AS 'Draft Updated By',
--SELECT * FROM ODRF WHERE DocEntry=4962
--SELECT * FROM ODRF WHERE DocEntry=4963
--SELECT * FROM ORDR WHERE DocNum=519836