
--DOCS. FOR CONFIRMATION

--DECLARE @WddCode	INT
--DECLARE @Status		VARCHAR(1)


SELECT DISTINCT


T0.WddCode,
CASE 
	WHEN T0.ObjType=17		THEN 'Sales Order'
END 'Document Type',
(SELECT U_NAME FROM [OUSR] where USERID=T0.OwnerID)			AS 'Originator',
T3.Name														AS 'Template',
T0.DocDate,
CASE 
	WHEN T0.Status='W'	THEN 'Pending'
	WHEN T0.Status='Y'	THEN 'Approved'
	WHEN T0.Status='N'	THEN 'Rejected'
	WHEN T0.Status='P'	THEN 'Generated'
	WHEN T0.Status='A'	THEN 'Generated by Authorizer'
	WHEN T0.Status='C'	THEN 'Canceled'
END Status,
T4.Name														AS 'Confirmation Level',
T0.IsDraft,
CASE
	WHEN T0.ProcesStat='W'	THEN 'Pending'
	WHEN T0.ProcesStat='Y'	THEN 'Approved'
	WHEN T0.ProcesStat='N'	THEN 'Rejected'
	WHEN T0.ProcesStat='P'	THEN 'Generated'
	WHEN T0.ProcesStat='A'	THEN 'Generated by Authorizer'
	WHEN T0.ProcesStat='C'	THEN 'Canceled'
END 'ProcesStat',
T0.CurrStep,
T0.DraftEntry,
(SELECT DocNum  FROM ORDR WHERE draftKey=T0.DraftEntry)		AS 'DocumentNo.'


FROM OWDD	T0

	INNER  JOIN ODRF T1  ON  T1.DocEntry= T0.DraftEntry
	INNER  JOIN OUSR T2  ON  T2.USERID= T0.OwnerID
	INNER  JOIN OWTM T3  ON  T3.WtmCode=T0.WtmCode
	INNER  JOIN OWST T4	 ON  T4.WstCode=T0.CurrStep
	

WHERE 
T0.DocDate >='2022-03-09 00:00:00'	AND 
T0.DocDate <='2022-03-09 00:00:00'	AND 
T0.ObjType=17
	





