
SELECT 

T2.DocNum			AS  'OrderNum'

FROM DLN1 T0    WITH (NOLOCK)

	RIGHT OUTER JOIN OINV  T1	ON T1.DocEntry=T0.TrgetEntry  	LEFT  OUTER JOIN ORDR  T2	ON T2.DocNum=T0.BaseRef AND T2.DocEntry=T0.BaseEntry	LEFT  OUTER JOIN OCRD  T3   ON T3.CardCode=T1.CardCode	LEFT  OUTER JOIN OSLP  T4	ON T4.SlpCode=T1.SlpCode	LEFT  OUTER JOIN INV12 T5	ON T5.DocEntry=T1.DocEntry	LEFT  OUTER JOIN INV1  T6   ON T6.DocEntry=T1.DocEntry	LEFT  OUTER JOIN OITM  T7   ON T7.ItemCode=T6.ItemCode



WHERE
	T0.[DocDate] BETWEEN '2022-02-01' AND '2022-02-28'	AND
	T0.[CANCELED] = 'N'				  AND T1.QryGroup1='N'


-- Delivery
--SELECT * FROM ODLN WHERE DocNum=607924
--SELECT * FROM DLN1 WHERE DocEntry=10973

--Invoice
--SELECT * FROM OINV WHERE DocNum=709307
--SELECT * FROM INV1 WHERE DocEntry=13881

-- Credit Memo
--SELECT * FROM ORIN T0 WHERE T0.DocNum=645
--SELECT * FROM RIN1 T0 WHERE T0.DocEntry=645