	
SELECT 
T0.WddCode, 
CASE 
	WHEN T1.ObjType=17		THEN 'Sales Order'
END 'Document Type',
(SELECT U_NAME FROM [OUSR] where USERID=T0.UserID)			AS 'Draft Updated By',
T3.Name														AS 'Template',
T0.UpdateDate,
CASE 
	WHEN T0.Status='W'	THEN 'Pending'
	WHEN T0.Status='Y'	THEN 'Approved' + ',' + ' ' + 'Issue Production Ticket'
	WHEN T0.Status='N'	THEN 'Rejected'
	WHEN T0.Status='P'	THEN 'Generated'
	WHEN T0.Status='A'	THEN 'Generated by Authorizer'
	WHEN T0.Status='C'	THEN 'Canceled'
END Status,
T2.Name														AS 'Confirmation Level',
T1.IsDraft,
T0.StepCode,
T1.DraftEntry

FROM WDD1 T0

	INNER  JOIN OWDD T1  ON  T1.WddCode=T0.WddCode
	INNER  JOIN OWST T2	 ON  T2.WstCode=T0.StepCode
	INNER  JOIN OWTM T3  ON  T3.WtmCode=T1.WtmCode

WHERE 
--T0.WddCode=5328							AND 
T0.StepCode=20 AND	T0.Status='Y'		AND
T0.CreateDate >='2022-03-09 00:00:00'	AND 
T0.CreateDate <='2022-03-09 00:00:00'	


--SELECT * FROM ORDr WHERE DocNum=519837
--SELECT * FROM ODRF WHERE DocEntry=4962

--SELECT * FROM OWDD WHERE WddCode=5328