

--SELECT DocEntry, DocNum FROM ORCT  WHERE DocEntry=8181
--SELECT * FROM RCT2 WHERE DocEntry=8180
--SELECT * FROM OINV WHERE DocNum=707929


--SELECT DocEntry, DocNum, PeyMethod, CardCode FROM ORDR WHERE DocNum=520406
----SELECT DocEntry, DocNum, PeyMethod FROM OINV WHERE DocNum=710686
----SELECT * FROM ODLN WHERE DocNum=609121
--SELECT * FROM DLN1 WHERE DocEntry=12170
SELECT * FROM OINV WHERE DocNum=710687
SELECT * FROM OINV WHERE DocNum=710686
--SELECT * FROM INV1 WHERE DocEntry=15261



--SELECT * FROM ORCT WHERE DocNum=8180
--SELECT * FROM ORCT WHERE DocNum=8181
--SELECT * FROM ORCT WHERE DocNum=8147
--SELECT * FROM RCT2	 WHERE DocEntry=15261


--SELECT * FROM OCRD WHERE GroupNum=31 AND SlpCode=7
--SELECT DocEntry, DocNum, PeyMethod FROM OINV WHERE  GroupNum=31 AND SlpCode=7



SELECT * FROM ODPI WHERE DocNum=36
SELECT * FROM ODPI WHERE DocNum=37

--SELECT *

--FROM OCRD T0

--	INNER JOIN ORCT T1 ON T0.CardCode=T1.CardCode
--	INNER JOIN RCT2 T3 ON T3.DocNum=T1.DocNum
--	INNER JOIN OINV T4 ON T4.DocEntry=T3.DocEntry AND T3.InvType='13'